// The skills a person can rate themselves against, and the scale they rate on.
//
// The 189 skills are the self-assessment tool's own list, taken from
// <https://ddat-capability-framework.service.gov.uk/skills> and compared with
// the catalogue in `spec/skills.md`. An `id` is the column heading in an
// export, so it is a stable key: never rename one. The role summaries name 183
// skills, so a few of these have no skill page on this site.

export type SelfAssessmentSkill = { id: string; title: string };

export type RatingStep = { value: number; label: string; meaning: string };

/** The 0–4 scale, as the standalone tool has always had it. */
export const RATING_SCALE: readonly RatingStep[] = [
  { value: 0, label: 'None', meaning: 'You have not worked with this' },
  { value: 1, label: 'Awareness', meaning: 'You know what it is and why it matters' },
  { value: 2, label: 'Working', meaning: 'You do it with support' },
  {
    value: 3,
    label: 'Practitioner',
    meaning: 'You do it unsupported, and handle the usual exceptions'
  },
  { value: 4, label: 'Expert', meaning: 'You set the approach and develop others in it' }
];

export const SELF_ASSESSMENT_SKILLS: readonly SelfAssessmentSkill[] = [
  { id: 'accessibility', title: 'Accessibility' },
  { id: 'adapting-to-delivery-methodologies', title: 'Adapting to delivery methodologies' },
  { id: 'agile-and-lean-practices', title: 'Agile and Lean practices' },
  { id: 'agile-research-practices', title: 'Agile research practices' },
  { id: 'agile-working', title: 'Agile working' },
  { id: 'agile-working-content-design', title: 'Agile working (content design)' },
  { id: 'analysis', title: 'Analysis' },
  { id: 'analysis-and-insight', title: 'Analysis and insight' },
  { id: 'analysis-and-synthesis', title: 'Analysis and synthesis' },
  { id: 'analysis-and-synthesis-data-ethics', title: 'Analysis and synthesis (data ethics)' },
  { id: 'applied-maths-statistics-and-scientific-practices', title: 'Applied maths, statistics and scientific practices' },
  { id: 'applied-social-sciences', title: 'Applied social sciences' },
  { id: 'applying-statistical-and-analytical-tools-and-techniques', title: 'Applying statistical and analytical tools and techniques' },
  { id: 'applying-user-centred-insights', title: 'Applying user-centred insights' },
  { id: 'architect-for-the-whole-context', title: 'Architect for the whole context' },
  { id: 'architecture-communication', title: 'Architecture communication' },
  { id: 'asset-and-configuration-management', title: 'Asset and configuration management' },
  { id: 'availability-and-capacity-management', title: 'Availability and capacity management' },
  { id: 'business-analysis-it-operations', title: 'Business analysis (IT operations)' },
  { id: 'business-architecture', title: 'Business architecture' },
  { id: 'business-modelling', title: 'Business modelling' },
  { id: 'business-process-improvement', title: 'Business process improvement' },
  { id: 'capability-building-for-digital-and-data-teams', title: 'Capability building for digital, data and technology' },
  { id: 'change-management', title: 'Change management' },
  { id: 'changing-security-culture', title: 'Changing security culture' },
  { id: 'coding-and-scripting', title: 'Coding and scripting' },
  { id: 'commercial-management', title: 'Commercial management' },
  { id: 'commercial-perspective', title: 'Commercial perspective' },
  { id: 'communicating-analysis-and-insight', title: 'Communicating analysis and insight' },
  { id: 'communicating-between-the-technical-and-non-technical', title: 'Communicating between the technical and non-technical' },
  { id: 'communicating-data', title: 'Communicating data' },
  { id: 'communicating-information', title: 'Communicating information' },
  { id: 'communication-data-ethics', title: 'Communication (data ethics)' },
  { id: 'communication-security-architect', title: 'Communication (security architect)' },
  { id: 'community-collaboration', title: 'Community collaboration' },
  { id: 'consultancy', title: 'Consultancy' },
  { id: 'content-concepts-and-prototyping', title: 'Content concepts and prototyping' },
  { id: 'context-problem-and-option-analysis', title: 'Context, problem and option analysis' },
  { id: 'continual-service-improvement', title: 'Continual service improvement' },
  { id: 'continuity-management', title: 'Continuity management' },
  { id: 'creating-value-for-money', title: 'Creating value for money' },
  { id: 'customer-service-management', title: 'Customer service management' },
  { id: 'cyber-incident-management', title: 'Cyber incident management' },
  { id: 'cyber-risk-management', title: 'Cyber risk management' },
  { id: 'cyber-security-governance', title: 'Cyber security governance' },
  { id: 'data-analysis-and-synthesis', title: 'Data analysis and synthesis' },
  { id: 'data-architecture', title: 'Data architecture' },
  { id: 'data-compliance-and-security', title: 'Data compliance and security' },
  { id: 'data-development-process', title: 'Data development process' },
  { id: 'data-engineering-and-manipulation', title: 'Data engineering' },
  { id: 'data-ethics-and-privacy', title: 'Data ethics and privacy' },
  { id: 'data-governance', title: 'Data governance' },
  { id: 'data-governance-data-architect', title: 'Data governance (data architect)' },
  { id: 'data-governance-leadership', title: 'Data governance leadership' },
  { id: 'data-innovation', title: 'Data innovation' },
  { id: 'data-integration-design', title: 'Data integration design' },
  { id: 'data-life-cycle', title: 'Data life cycle' },
  { id: 'data-literacy-improvement', title: 'Data literacy improvement' },
  { id: 'data-management', title: 'Data management' },
  { id: 'data-maturity', title: 'Data maturity' },
  { id: 'data-modelling', title: 'Data modelling' },
  { id: 'data-modelling-cleansing-and-enrichment', title: 'Data modelling, cleansing and enrichment' },
  { id: 'data-preparation-and-linkage', title: 'Data preparation and linkage' },
  { id: 'data-risk-management', title: 'Data risk management' },
  { id: 'data-science-innovation', title: 'Data science innovation' },
  { id: 'data-standards', title: 'Data standards' },
  { id: 'data-visualisation', title: 'Data visualisation' },
  { id: 'defining-and-managing-business-needs-user-needs-and-requirements', title: 'Defining and managing business needs, user needs and requirements' },
  { id: 'delivering-business-impact', title: 'Delivering business impact' },
  { id: 'delivering-business-impact-through-data', title: 'Delivering business impact through data' },
  { id: 'design-communication', title: 'Design communication' },
  { id: 'designing-and-executing-tests', title: 'Designing and executing tests' },
  { id: 'designing-for-everyone', title: 'Designing for everyone' },
  { id: 'designing-secure-systems', title: 'Designing secure systems' },
  { id: 'designing-strategically', title: 'Designing strategically' },
  { id: 'designing-together', title: 'Designing together' },
  { id: 'developing-code-for-analysis', title: 'Developing code for analysis' },
  { id: 'developing-data-science-capability', title: 'Developing data science capability' },
  { id: 'development-process-optimisation', title: 'Development process optimisation' },
  { id: 'digital-and-data-systems-analysis', title: 'Digital and data systems analysis' },
  { id: 'empathy-and-inclusivity', title: 'Empathy and inclusivity' },
  { id: 'enabling-and-informing-risk-based-decisions', title: 'Enabling and informing risk-based decisions' },
  { id: 'ensuring-resilience-of-digital-data-and-technology', title: 'Ensuring resilience of digital, data and technology' },
  { id: 'enterprise-and-business-architecture-business-analyst', title: 'Enterprise and business architecture (business analyst)' },
  { id: 'enterprise-architecture', title: 'Enterprise architecture' },
  { id: 'evaluation-delivery', title: 'Evaluation delivery' },
  { id: 'evaluation-planning-and-strategy', title: 'Evaluation planning and strategy' },
  { id: 'evidence-based-design', title: 'Evidence-based design' },
  { id: 'financial-decision-making-for-technology', title: 'Financial decision making for technology' },
  { id: 'financial-management', title: 'Financial management' },
  { id: 'financial-management-for-digital-data-and-technology', title: 'Financial management for digital, data and technology' },
  { id: 'financial-ownership', title: 'Financial ownership' },
  { id: 'governance-and-assurance', title: 'Governance and assurance' },
  { id: 'governance-and-assurance-accessibility', title: 'Governance and assurance (accessibility)' },
  { id: 'incident-management', title: 'Incident management' },
  { id: 'inclusive-research', title: 'Inclusive research' },
  { id: 'information-security', title: 'Information security' },
  { id: 'innovation-in-digital-and-data', title: 'Innovation in digital, data and technology' },
  { id: 'iterative-design', title: 'Iterative design' },
  { id: 'it-infrastructure', title: 'IT infrastructure' },
  { id: 'service-reporting', title: 'IT service reporting' },
  { id: 'leadership-and-guidance', title: 'Leadership and guidance' },
  { id: 'leadership-and-guidance-frontend-developer', title: 'Leadership and guidance (frontend developer)' },
  { id: 'leading-design', title: 'Leading design' },
  { id: 'leading-digital-products-and-services', title: 'Leading digital products and services' },
  { id: 'leading-performance-and-benefits', title: 'Leading performance and benefits' },
  { id: 'life-cycle-management', title: 'Life cycle management' },
  { id: 'maintaining-delivery-momentum', title: 'Maintaining delivery momentum' },
  { id: 'making-and-guiding-decisions', title: 'Making and guiding decisions' },
  { id: 'making-a-process-work', title: 'Making a process work' },
  { id: 'making-architectural-decisions', title: 'Making architectural decisions' },
  { id: 'making-strategic-performance-led-change', title: 'Making strategic performance-led change' },
  { id: 'managing-a-data-project', title: 'Managing a data project' },
  { id: 'managing-decisions-and-risks', title: 'Managing decisions and risks' },
  { id: 'managing-product-outcomes', title: 'Managing product outcomes' },
  { id: 'managing-reporting-and-resolving-defects', title: 'Managing, reporting and resolving defects' },
  { id: 'metadata-management', title: 'Metadata management' },
  { id: 'methods-and-tools', title: 'Methods and tools' },
  { id: 'modern-development-standards', title: 'Modern development standards' },
  { id: 'monitoring-and-evaluation-across-the-product-life-cycle', title: 'Monitoring and evaluation across the product life cycle' },
  { id: 'operational-management', title: 'Operational management' },
  { id: 'optimising-technology-and-data-architecture', title: 'Optimising technology and data architecture' },
  { id: 'ownership-and-initiative', title: 'Ownership and initiative' },
  { id: 'performance-measurement', title: 'Performance measurement' },
  { id: 'planning', title: 'Planning' },
  { id: 'problem-definition-and-shaping', title: 'Problem definition and shaping' },
  { id: 'problem-management', title: 'Problem management' },
  { id: 'product-and-service-monitoring', title: 'Product and service monitoring' },
  { id: 'product-leadership', title: 'Product leadership' },
  { id: 'product-management', title: 'Product management' },
  { id: 'product-ownership-data-ethics', title: 'Product ownership (data ethics)' },
  { id: 'programming-and-build-data-and-analytics-engineering', title: 'Programming and build (data and analytics engineering)' },
  { id: 'programming-and-build-data-science', title: 'Programming and build (data science)' },
  { id: 'programming-and-build-frontend-developer', title: 'Programming and build (frontend developer)' },
  { id: 'programming-and-build-software-engineering', title: 'Programming and build (software engineering)' },
  { id: 'prototyping', title: 'Prototyping' },
  { id: 'verification-and-validation-of-data-and-analysis', title: 'Quality assurance of data and analysis' },
  { id: 'research-and-innovation', title: 'Research and innovation' },
  { id: 'research-management-leadership-and-assurance', title: 'Research management, leadership and assurance' },
  { id: 'security-architecture', title: 'Security architecture' },
  { id: 'security-technology', title: 'Security technology' },
  { id: 'service-focus', title: 'Service focus' },
  { id: 'service-management-framework-knowledge', title: 'Service management framework knowledge' },
  { id: 'service-support', title: 'Service support' },
  { id: 'shaping-the-direction-of-organisational-strategy-through-digital-data-and-technology', title: 'Shaping the direction of organisational strategy through digital, data and technology' },
  { id: 'stakeholder-relationship-management', title: 'Stakeholder relationship management' },
  { id: 'stakeholder-relationship-management-content-design', title: 'Stakeholder relationship management (content design)' },
  { id: 'stakeholder-relationship-management-it-operations', title: 'Stakeholder relationship management (IT operations)' },
  { id: 'strategic-cyber-security-planning', title: 'Strategic cyber security planning' },
  { id: 'strategic-data-planning', title: 'Strategic data planning' },
  { id: 'strategic-design-and-business-change', title: 'Strategic design and business change' },
  { id: 'strategic-ownership', title: 'Strategic ownership' },
  { id: 'strategic-technology-planning', title: 'Strategic technology planning' },
  { id: 'strategic-thinking', title: 'Strategic thinking' },
  { id: 'strategic-thinking-content-design', title: 'Strategic thinking (content design)' },
  { id: 'strategy-design', title: 'Strategy design' },
  { id: 'systems-design', title: 'Systems design' },
  { id: 'systems-design-frontend-developer', title: 'Systems design (frontend developer)' },
  { id: 'systems-integration', title: 'Systems integration' },
  { id: 'systems-integration-frontend-developer', title: 'Systems integration (frontend developer)' },
  { id: 'team-dynamics-and-collaboration', title: 'Team dynamics and collaboration' },
  { id: 'technical-design-throughout-the-life-cycle', title: 'Technical design throughout the life cycle' },
  { id: 'technical-specialism', title: 'Technical specialism' },
  { id: 'technical-understanding', title: 'Technical understanding' },
  { id: 'technical-understanding-accessibility', title: 'Technical understanding (accessibility)' },
  { id: 'technical-understanding-performance-analyst', title: 'Technical understanding (performance analyst)' },
  { id: 'technical-understanding-user-centred-design', title: 'Technical understanding (user-centred design)' },
  { id: 'technology-architecture', title: 'Technology architecture' },
  { id: 'technology-evaluation', title: 'Technology evaluation' },
  { id: 'test-analysis', title: 'Test analysis' },
  { id: 'test-and-quality-planning', title: 'Test and quality planning' },
  { id: 'test-engineering', title: 'Test engineering' },
  { id: 'testing', title: 'Testing' },
  { id: 'testing-business-analysis', title: 'Testing (business analysis)' },
  { id: 'troubleshooting-and-problem-resolution', title: 'Troubleshooting and problem resolution' },
  { id: 'turning-business-problems-into-data-design', title: 'Turning business problems into data design' },
  { id: 'understanding-analysis-across-the-product-life-cycle', title: 'Understanding analysis across the product life cycle' },
  { id: 'understanding-product-delivery', title: 'Understanding product delivery' },
  { id: 'understanding-security-implications-of-transformation', title: 'Understanding security implications of transformation' },
  { id: 'user-centred-analysis', title: 'User-centred analysis' },
  { id: 'user-centred-content-design', title: 'User-centred content design' },
  { id: 'user-centred-practice-and-advocacy', title: 'User-centred practice and advocacy' },
  { id: 'user-experience-analysis', title: 'User experience analysis' },
  { id: 'user-focus', title: 'User focus' },
  { id: 'user-focus-content-design', title: 'User focus (content design)' },
  { id: 'user-focus-frontend-developer', title: 'User focus (frontend developer)' },
  { id: 'user-research-methods', title: 'User research methods' },
  { id: 'web-performance-optimisation', title: 'Web performance optimisation' },
  { id: 'working-within-constraints-performance-analyst', title: 'Working within constraints (performance analyst)' },
];
